name: cse-lbds
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # nginx will be restarted every 1 month
    command: '/bin/sh -c ''while :; do sleep 720h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/dns-nsone:v1.18.0
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # Certbot will be restarted after 12g everyday (by execute the renew command)
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jobe:
    image: trampgeek/jobeinabox
    container_name: jobe
    restart: always
    ports:
      - '4000:80'

  backend:
    build:
      context: ./server
    container_name: server
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
      - jobe
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - JOBE_URL=http://jobe/jobe/index.php/restapi/
volumes:
  postgres_data:

# docker compose -p cse-lbds up -d
